VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "database" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    db.vm.hostname = "Datenbank1"
    db.vm.network "private_network", ip: "192.168.69.144"
    db.vm.provision "shell", path: "db.sh"
  end


  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "Webserver1"

