VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "datenbanklb2" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    db.vm.hostname = "Datenbank1"
    db.vm.network "private_network", ip: "192.168.69.144"
    db.vm.provision "shell", path: "db.sh"
  end


  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "Webserver1"
    web.vm.network "private_network", ip:"192.168.69.145" 
    web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512" 
    end

  
  web.vm.synced_folder ".", "/var/www/html"  
  web.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get -y install debconf-utils apache2 nmap
  sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin'
	sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin'
	sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client  


  sudo mkdir /usr/share/adminer
	sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
	sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php


    

