---
# Apache, MySQL, PHP, Redis and PhpMyAdmin
# SSL is preconfigured.
# Imagemagick and XDebug are activated.
#
# Run with 
# docker-compose up -d
#
version: "0"
services:
# --- MySQL 5.7
#
mysql:
container_name: "lb3-mysql"
image: bitnami/mysql:5.7
environment:
- MYSQL_ROOT_PASSWORD=Gjilani123
- MYSQL_USER=admin
- MYSQL_PASSWORD=Gjilani123
ports:
- '3306:3306'
volumes:
- d/m300-rep/M300-Services/LB3/data:/bitnami/mysql/data
# --- PHP 7.4
#
php:
container_name: "lb3-php"
image: bitnami/php-fpm:7.4
depends_on:
- redis
volumes:
- /m300-rep/M300-Services/LB3/info.php:/app:delegated
- .//php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro
# --- Apache 2.4
#
apache:
container_name: "lb3-apache"
image: bitnami/apache:2.4
ports:
- '80:8080'
- '443:8443'
depends_on:
      - php
    volumes:
      - /m300-rep/M300-Services/LB3/info.php:/app:delegated
      - /m300-rep/M300-Services/LB3/my_vhost.conf:/vhosts/myapp.conf:ro
      - /m300-rep/M300-Services/LB3/server.key:/certs
      # Use this for bitnami's builtin certs:
      # /m300-rep/M300-Services/LB3/server.key:/opt/bitnami/apache2/conf/bitnami/certs
