version: "3"
services:
  db:
    # Wir benutzen ein mariadb-Image, wir können jedoch auch das mysql-Image benutzen, indem wir es auskommentieren.
    image: mariadb:10.6.4-focal
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060



  